layout_spectrum: 0.05383414519019425
typography_spectrum: 0.7042653218377382
color:
  brandStrength: 0.7171360533684492
  lightness: 0.09396201046183705
  saturation: 0.08630610932596028
  rhythmicContrast: 0.08176148938946426
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
author:
  name: Jagnoor
  email: jagnoor@msn.com
  url: 'https://www.facebook.com/jagnoorphotography/'
name: Jagnoor Singh
navigation:
  - name: Facebook - JagnoorPhotography
    url: 'https://www.facebook.com/jagnoorphotography/'
    type: external
  - name: Flickr- JagnoorPhotography
    url: 'https://www.flickr.com/photos/jagnoor/'
    type: external
  - name: Twitter- @JAGpictures
    url: 'https://twitter.com/JAGpictures'
    type: external
title: Jagnoor Photography
description: 'If a picture is worth a thousand words, then let me share my novel with you'
