layout_spectrum: 0.20327555830590427
typography_spectrum: 0.8824269683100283
color:
  brandStrength: 0.012270546751096845
  lightness: 0.43601676006801426
  saturation: 0.16701988084241748
  rhythmicContrast: 0.2642194938380271
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
author:
  name: Jagnoor
  email: jagnoor@msn.com
  url: 'https://www.facebook.com/jagnoorphotography/'
name: Jagnoor Singh
title: Jagnoor Photography
description: 'If a picture is worth a thousand words, then let me share my novel with you'
