layout_spectrum: 0.8328205123543739
typography_spectrum: 0.7385635925456882
color:
  brandStrength: 0.39213618682697415
  lightness: 0.40842145960778
  saturation: 0.861849861452356
  rhythmicContrast: 0.2123939711600542
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
author:
  name: Jagnoor
  email: jagnoor@msn.com
  url: 'https://www.facebook.com/jagnoorphotography/'
name: Jagnoor Singh
navigation:
  - name: Facebook - JagnoorPhotography
    url: 'https://www.facebook.com/jagnoorphotography/'
    type: external
  - name: Flickr- JagnoorPhotography
    url: 'https://www.flickr.com/photos/jagnoor/'
    type: external
  - name: Twitter- @JAGpictures
    url: 'https://twitter.com/JAGpictures'
    type: external
title: Jagnoor Photography
description: 'If a picture is worth a thousand words, then let me share my novel with you'
