typography_spectrum: 0.5085084408055991
color:
  brandStrength: 0.35914380685426295
  lightness: 0.26929475949145854
  saturation: 0.3453854941762984
  rhythmicContrast: 0.3239929380360991
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.43452987796626985
author:
  name: Jagnoor
  email: jagnoor@msn.com
  url: 'https://www.facebook.com/jagnoorphotography/'
name: Jagnoor Singh
title: Jagnoor Photography
description: 'If a picture is worth a thousand words, then let me share my novel with you'
