layout_spectrum: 0.5175635654013604
typography_spectrum: 0.6796004818752408
color:
  brandStrength: 0.25731628062203526
  lightness: 0.4675242332741618
  saturation: 0.34889490623027086
  rhythmicContrast: 0.6551996956113726
  brandColors:
    - '#DDDCC5'
    - '#958976'
    - '#611427'
    - '#1D2326'
    - '#6A6A61'
author:
  name: Jagnoor
  email: jagnoor@msn.com
  url: 'https://www.facebook.com/jagnoorphotography/'
name: Jagnoor Singh
navigation:
  - name: Facebook - JagnoorPhotography
    url: 'https://www.facebook.com/jagnoorphotography/'
    type: external
  - name: Flickr- JagnoorPhotography
    url: 'https://www.flickr.com/photos/jagnoor/'
    type: external
  - name: Twitter- @JAGpictures
    url: 'https://twitter.com/JAGpictures'
    type: external
title: Jagnoor Photography
description: 'If a picture is worth a thousand words, then let me share my novel with you'
