typography_spectrum: 0.6651151455007493
color:
  brandStrength: 0.8503947607241571
  lightness: 0.6709196530282497
  saturation: 0.8078957474790514
  rhythmicContrast: 0.47455512126907706
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.3476252865511924
author:
  name: Jagnoor
  email: jagnoor@msn.com
  url: 'https://www.facebook.com/jagnoorphotography/'
name: Jagnoor Photography
navigation:
  - name: Facebook - JagnoorPhotography
    url: 'https://www.facebook.com/jagnoorphotography/'
    type: external
  - name: Flickr- JagnoorPhotography
    url: 'https://www.flickr.com/photos/jagnoor/'
    type: external
title: Jagnoor Photography
description: 'If a picture is worth a thousand words, then let me share my novel with you'
